config/routes.rb
Ticketee::Application.routes.draw do

  root to: "projects#index"
  resources :projects do 
    resources :tickets 
  end

  namespace :admin do
    root to: "base#index" 
    resources :users do 
      resources :permissions

      put "permissions", to: "permissions#set",
                         as: "set_permissions"
    end
  end

  resources :files

  resources :users

  get "/signin", to: "sessions#new", as: "signin"
  post "/signin", to: "sessions#create"
  delete "/signout", to: "sessions#destroy", as: "signout"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    <% if content_for?(:title) %>
      <%= yield(:title) %>
    <% else %>
      Ticketee
    <% end %>
  </title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav>
    <% if current_user %>
      Signed in as <%= current_user.email %>
      <%= link_to "Sign out", signout_path, method: :delete %>
      <% admins_only do %>
        <%= link_to "Admin", admin_root_path %>
      <% end %>
    <% else %>
      <ul>
        <li><%= link_to "Sign up", new_user_path %></li>
        <li><%= link_to "Sign in", signin_path %></li>
      </ul>
    <% end %>
  </nav>

<% flash.each do |key, value| %>
  <div class='flash' id='<%= key %>'>
    <%= value %>
  </div>
<% end %>  

<%= yield %>

</body>
</html>